
pool:
  vmImage: ubuntu-latest

variables:
  new_value: 'hoge'

steps:
  - bash: echo hoge
  - bash: echo variables['new_value']
  - bash: echo pass
    condition: |
      eq('hoge', variables['new_value'])
  - bash: echo pass
    condition: |
      eq('fuga', variables['new_value'])

